### ISSUE TITLE
AutomaticDecompression does not always return decoded content

### ISSUE THREAD

**Issue by samusaran** [SharpTools/SharpReverseProxy#11]
I was trying to redirect request to www.google.com and the content that I read back with response.Content.ReadAsStringAsync() is seemingly random characters like:

`ï¿½ï¿½ï¿½Qdï¿½vï¿½{pÌ€ï¿½Yï¿½ï¿½Pï¿½HÈ¼`ï¿½Ç¯?ï¿½ï¿½ï¿½ï¿½qï¿½ï¿½iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Vï¿½ï¿½ï¿½ï¿½},Ü¤JWï¿½,ï¿½ï¿½3ï¿½s9I5ï¿½JUï¿½($ï`

Am I reading the content wrong? Is it still encrypted? Do I need to decrypt the content manually?
Note that this happen if the Request is either http or https.

Thanks!

**Comment by andrecarlucci** [comment]
Hi @samusaran ,

That's happening because google is returning the body using G-ZIP.
Here is an example that would work in this case:

```cs
         app.UseProxy(new List<ProxyRule> {
                new ProxyRule {
                    Matcher = uri => uri.AbsoluteUri.Contains("/google"),
                    Modifier = (req, user) => {
                        req.RequestUri = new Uri("https://www.google.com/search?q=sharpreverseproxy");
                        req.Headers.AcceptEncoding.Clear();
                        req.Headers.AcceptEncoding.Add(new System.Net.Http.Headers.StringWithQualityHeaderValue("identity"));
                    },
                    PreProcessResponse = false,
                    ResponseModifier = async (res, context) => {
                        var bytes = await res.Content.ReadAsByteArrayAsync();
                        var html = Encoding.UTF8.GetString(bytes);
                        html = html.Replace("SharpReverseProxy", "SharpReverseProxy Rocks!");
                        bytes = Encoding.UTF8.GetBytes(html);
                        await context.Response.Body.WriteAsync(bytes, 0, bytes.Length);
                    }
                }
            });
```

**Comment by samusaran** [comment]
I'll try your solution in a moment.
Another question: I set up AutomaticDecompression on GZip into the proxy settings like this:

```csharp
app.UseProxy(new ProxyOptions
{
    ProxyRules = new List<ProxyRule>
    {
        new ProxyRule {
            Matcher = uri => Task.Run(async () => await ReverseProxyDelegates.ProxyUrlMatcher(uri, serviceProvider)).Result,
            Modifier = async (req, user) => await ReverseProxyDelegates.ProxyRequestModifier(app, serviceProvider, req, user),
            ResponseModifier = async (res, ctx) => await ReverseProxyDelegates.ProxyResponseModifier(res, ctx),
            PreProcessResponse = false, // la response la processo a mano
            RequiresAuthentication = false // non richiedo l'autenticazione, almeno finchè non viene implementata
        }
    },
    Reporter = (r) =>
    {
        if (r.ProxyStatus == ProxyStatus.Proxied)
            logger.LogInformation($"Proxied request from {r.OriginalUri} to {r.ProxiedUri} took: {r.Elapsed}");
    },
    BackChannelMessageHandler = new System.Net.Http.HttpClientHandler()
    {
        AutomaticDecompression = System.Net.DecompressionMethods.GZip | System.Net.DecompressionMethods.Deflate,
        AllowAutoRedirect = true,
    }
});
```
Is it not enough to read Gzip compressed response?

**Comment by samusaran** [comment]
Your solution is working, but I still don't understand why setting the AutomaticDecompression property does not actually trigger the GZip decompression.

**Comment by andrecarlucci** [comment]
Hi @samusaran 
No idea too. It was supposed to work :(

**Comment by samusaran** [comment]
Hi @andrecarlucci , I've found the issue about Google or other "strange" sites.

Google accepts `gzip`, `deflate` and `br`, and in my case it was encoding data with Brotli algorithm, which is not supported in `System.Net.DecompressionMethods`.

So the AutomaticDecompression actually works as-is, but instead of accepting only `identity`, I have changed it to accept `gzip` and `deflate` and not `br`.

You can close the issue :)

Still thanks a lot for this middleware.
