### ISSUE TITLE
Response has already started before ResponseModifier is called

### ISSUE THREAD

**Issue by Mike-Bell** [SharpTools/SharpReverseProxy#12]
Currently (1.3.15), if I supply a `ResponseModifier` to my `ProxyRule` and leave the `PreProcessResponse` as the default `true`, then the response has already started `(response.HasStarted == true)` by the time my `ResponseModifier` is called. This is an issue because modifications made within the `ResponseModifier` may not be sent to the client when that is the case. 

My current workaround is to set `PreProcessResponse` to false, then in my ResponseModifier, do whatever modifications I need, then execute code which I copy-pasted from https://github.com/SharpTools/SharpReverseProxy/blob/master/src/SharpReverseProxy/ProxyMiddleware.cs, specifically:

```csharp
      public static async Task CopyProxiedResponseToContext( HttpResponseMessage responseMessage, HttpContext context )
      {
         // This is copied from https://github.com/SharpTools/SharpReverseProxy/blob/e6b5b3a559be01fd43b08006bec7eb9e9a7a0708/src/SharpReverseProxy/ProxyMiddleware.cs
         // There is currently an issue in that library where this code needs to execute after modifying headers because this code causes the response to start sending

         context.Response.StatusCode = (int) responseMessage.StatusCode;
         context.Response.ContentType = responseMessage.Content?.Headers.ContentType?.MediaType;
         foreach ( var header in responseMessage.Headers )
         {
            context.Response.Headers[header.Key] = header.Value.ToArray();
         }
         // SendAsync removes chunking from the response. 
         // This removes the header so it doesn't expect a chunked response.
         context.Response.Headers.Remove( "transfer-encoding" );

         if ( responseMessage.Content != null )
         {
            foreach ( var contentHeader in responseMessage.Content.Headers )
            {
               context.Response.Headers[contentHeader.Key] = contentHeader.Value.ToArray();
            }
            await responseMessage.Content.CopyToAsync( context.Response.Body );
         }
      }
```

**Comment by andrecarlucci** [comment]
Hi @Mike-Bell ,

The feature about rewriting the response was added later and I guess it didn't fit well the way it was implemented.

We can't change that without adding breaking changes so I guess we will have to rewrite this feature on version 2.0.

Btw, how would you like to be the api to achieve this (rewrite response)? I mean, what would be default, what optional and how to override the defaults in your option?
