### ISSUE TITLE
Should allow UseCookies option

### ISSUE THREAD

**Issue by Mike-Bell** [SharpTools/SharpReverseProxy#13]
Currently, `HttpClientHandler` uses the default setting for `UseCookies`, which I believe is `true`. This is a huge issue for sites using cookie-based authentication, as unauthenticated users will get someone else's cookie-based session.

Looks like this can probably be overcome by supplying my own HttpClientHandler to the ProxyOptions

**Comment by carlosmorcerf** [comment]
:+1:

**Comment by andrecarlucci** [comment]
Fixed on 2.0
