### ISSUE TITLE
Interrupting a browser request results in a TaskCancelledException in HttpClient.SendAsync

### ISSUE THREAD

**Issue by samusaran** [SharpTools/SharpReverseProxy#15]
When I'm loading a website through the reverse proxy, if I stop the request or click a link, the request get cancelled (and that's fine) but I see a `TaskCancelledException` being thrown.

I've tried to work around this problem changing the implementation of `ProxyTheRequest` and using `ContinueWith()` chained after the `SendAsync`, but I couldn't manage to let it work until I changed the `HttpCompletionOption` to `ResponseContentRead`, actually slowing the middleware.

I can't find any use to that exception, since I can't even return some response to the client due to the fact that the client itself terminated the request.

Could it be feasible to catch the `TaskCancelledException` around `await ProxyTheRequest(context, proxyRequest, matchedRule);`?

**Comment by andrecarlucci** [comment]
Solved on v2.0
