### ISSUE TITLE
Rewrite WebSocket request

### ISSUE THREAD

**Issue by Yavor81** [SharpTools/SharpReverseProxy#2]
Hi, 
How can I rewrite WebSocket requests using the SharpReverseProxy?
My scenario is that I have an ASP.NET website and I want to redirect to specific url only if a user is authenticated. I have managed to redirect the WebSocket request in one way, but cannot handle the incoming request from the WebSocket to relay it back to the client.
Is this possible?

**Comment by andrecarlucci** [comment]
Hi @YavorTelerik,
Currently, not :(

As the actual communication after the handshake is done via a raw socket, you would have configure your app to use websockets (Microsoft.AspNetCore.WebSockets, app.UseWebSockets()) and write a middleware to start a socket connection to the configured proxied server and copy data from/to it.

The good: you would be able to do anything with the payloads, log, change, etc.
The bad: a little delay will be added to every connection and the client would think it is connected to the final server already before the second connection is actually completed.

It's definitely something we could add to SharpReverseProxy.

Here are some links to help:
https://radu-matei.github.io/blog/aspnet-core-websockets-middleware/
https://www.softfluent.com/blog/dev/2016/12/11/Using-Web-Sockets-with-ASP-NET-Core

**Comment by Yavor81** [comment]
Hi Andre,
Thank you for the detailed information. The articles are great. I was on the right direction but have an incomplete web socket handling.
What I understood from you is that once I receive a message from the client in my proxy middleware, I have to create new web socket client to the actual web socket server, relaying the message to it and simultaneously relay back the messages to the client. Is that correct?

**Comment by andrecarlucci** [comment]
Yes, that's it.
Unfortunately we're not in a network level to do that directly (like a firewall or gateway). Don't forget to check and notify both sides for disconnections :)

**Comment by Yavor81** [comment]
Hi again,
Thank you for your further directions.
I have issues with the connection state indeed when trying to redirect the received data to the web socket server. The communication breaks at some point but maybe it is something specific to my scenario, so I will continue investigating it.

**Comment by andrecarlucci** [comment]
Nice, let me know if you get it working or if you hit some wall :)

**Comment by andrecarlucci** [comment]
Hi @YavorTelerik ,
Did you manage to make it work?

**Comment by Trolldemorted** [comment]
@andrecarlucci Can we expect "native" ws support in SharpReverseProxy in the near future?
