### ISSUE TITLE
How is this Owin?

### ISSUE THREAD

**Issue by jtheisen** [SharpTools/SharpReverseProxy#20]
You're the second guy that advertises something as OWIN which turns out to be ASP.NET Core.

So maybe it's me who doesn't understand something here...

I have an ASP.NET 4 OWIN app, but it seems I can't use your proxy.

Why do you call this OWIN?

**Comment by SampathDilhan** [comment]
Perhaps you can try this: https://github.com/RoadTrain/ReverseProxyMiddleware

**Comment by jtheisen** [comment]
Was really more wondering about why it's called Owin - I will be using your proxy in a separate Core app then.

**Comment by jtheisen** [comment]
Also, I suggest putting the line `PreProcessResponse = false` in the response modifier sample. Took me a while to understand why I'm getting "response already consumed" exceptions.

**Comment by jtheisen** [comment]
But it's working now, pretty cool. Thanks a lot for this.

**Comment by andrecarlucci** [comment]
Hi @jtheisen ,

We call it OWIN because it is an OWIN Middleware according to the OWIN specification. It's just happen to be implemented as a .net standard package.

The problem is that the version of the netstandard used here is incompatible with your ASP.NET 4 App (actually, to the version of the .Net Framework you are using, not the ASP.NET). 

Cheers!

**Comment by jtheisen** [comment]
@andrecarlucci  Which version of the .NET Framework can I use this with an ASP.NET 4 App?

**Comment by andrecarlucci** [comment]
Check here:  https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by wazzamatazz** [comment]
@jtheisen is correct - this isn't OWIN. It's ASP.NET Core. You cannot use this middleware in an ASP.NET (not Core) application.

EDIT: don't get me wrong, your project is great; it's just misleading to say it's OWIN, because people using ASP.NET cannot use it!
