### ISSUE TITLE
How to implement basic authentication using SharpReverse

### ISSUE THREAD

**Issue by rifaterdemsahin** [SharpTools/SharpReverseProxy#25]
Pass through authentication to be able to serve ELK ? ( Kibana)

having documentation would be great with a sample implementation code on this issue.

Is this enough to collect the username and password?
RequiresAuthentication = true

**Comment by rifaterdemsahin** [comment]
Tried this without luck
![image](https://user-images.githubusercontent.com/5270036/47804320-681f9580-dd2c-11e8-9281-af518e9c9ebe.png)

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using SharpReverseProxy;

namespace BasicAuthPoc
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public void Configure(IApplicationBuilder app,
    IHostingEnvironment env,
    ILoggerFactory loggerFactory)
        {
            var byteArray = Encoding.ASCII.GetBytes("myuser:magicpassword");
            var authorizationHeaders = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(byteArray));

            app.UseProxy(new List<ProxyRule> {
        new ProxyRule {
            Matcher = uri => uri.AbsoluteUri.Contains("/api/"),
            Modifier = (req, user) => {
                req.Headers.Authorization=authorizationHeaders;
                
                var match = Regex.Match(req.RequestUri.AbsolutePath, "/api/(.+)service");
                req.RequestUri = new Uri(string.Format("https://bbc.co.uk",
                    match.Groups[1].Value,
                    req.RequestUri.Host,
                    req.RequestUri.AbsolutePath.Replace(match.Value, "/api/")
                    ));
            },
            RequiresAuthentication = false
        }
    },
            r =>
            {
                Debug.WriteLine($"Proxy: {r.ProxyStatus} Url: {r.OriginalUri} Time: {r.Elapsed}");
                if (r.ProxyStatus == ProxyStatus.Proxied)
                {
                    Debug.WriteLine($"        New Url: {r.ProxiedUri.AbsoluteUri} Status: {r.HttpStatusCode}");
                }
            });
        }
    }
}

```

**Comment by rifaterdemsahin** [comment]
Also asked in reddit
https://www.reddit.com/r/csharp/comments/9t9njy/attaching_basic_authentication/

**Comment by rifaterdemsahin** [comment]
tried post without luck
http://prntscr.com/ld737m

**Comment by andrecarlucci** [comment]
Hi @rifaterdemsahin ,

What exactly you're trying to do?
You already have basic authentication and want to divert the call when the user is not authenticated?
You want to use SharpReverseProxy to implement basic authentication?

RequiresAuthentication = true will make that rule to block any unauthenticated request with a 401 (if you use asp.net identity).

**Comment by rifaterdemsahin** [comment]
andre thanks for the response.
What exactly you're trying to do? You already have basic authentication and want to divert the call when the user is not authenticated?

**I want to add a basic authentication popup to my Kibana access.**

RequiresAuthentication = true will make that rule to block any unauthenticated request with a 401 (if you use asp.net identity). I need to be able to see the popup and enter the password and than continue to my kibana which is behind the apigateway(reversesharp)

These lines did not trigger that popup
var byteArray = Encoding.ASCII.GetBytes("myuser:magicpassword");
            var authorizationHeaders = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(byteArray));

Also tried 
 RequiresAuthentication = false
 RequiresAuthentication = true

they also did not help as well

**Comment by andrecarlucci** [comment]
Ok, now I got you. You want to protect Kibana with basic authentication, but all other request will pass through, right?

That won't work with SharpReverseProxy v1.x, but the functionality of blocking arbitrary requests is present on version 2.0-alpha.

Use the package:  [SharpReverseProxy v2.0.0-alpha9](https://www.nuget.org/packages/SharpReverseProxy/2.0.0-alpha9)

Then, write something like this:

```cs
    public void Configure(IApplicationBuilder app, IHostingEnvironment env) {
            app.UseProxy(new ProxyOptions {
                ProxyRules = new List<ProxyRule> {
                    new ProxyRule {
                        Matcher = async c => c.Url.Contains("/api/"),
                        RequestBlocker = async c => {
                            if (c.HttpRequest.Headers.TryGetValue("Authorization", out StringValues header) &&
                                await CheckPassword(header.FirstOrDefault().Replace("Basic ",""))) {
                                return RequestBlockerResult.NotBlocked();
                            }
                            var response = new HttpResponseMessage(HttpStatusCode.Unauthorized);
                            response.Headers.Add("WWW-Authenticate","Basic realm=\"Please, insert your password:\"");
                            return RequestBlockerResult.BlockAndRespondWith(response);
                        }
                    }
                }
            });
            app.UseMvc();
        }

        public Task<bool> CheckPassword(string base64string) {
            //put your login/pass logic here
            return Task.FromResult(false);
        }
```

I hope it helps.

Cheers!

**Comment by rifaterdemsahin** [comment]
thanks for the response by adding this we are not going to have any issues why https right ?

as we are changing the content that makes me think.

**Comment by andrecarlucci** [comment]
I should not, we are not changing the schema part.
Actually, if the server you are hosting the SharpReverseProxy is using https, even if the Kibana one is not, all content will be served with https :)
