### ISSUE TITLE
Is pass through authentication possible?

### ISSUE THREAD

**Issue by iosgitr** [SharpTools/SharpReverseProxy#7]
I use ARR in an anonymous IIS site as a reverse proxy to a web application that has HTTP authentication enabled.  It works well since ARR passes everything through including authentication to the appropriate back end system based on path.  I'm experimenting with replacing ARR/IIS with a self hosted ASP.NET Core 2.0 service running SharpReverseProxy but it seems like the 401 challenge responses from the back end systems aren't passing through ASP.NET Core and/or SharpReverseProxy to the client.  The client, per Fiddler, gets a 200 response but the content is a blank page with the text "401 unauthorized".  Should SharpReverseProxy be able to pass HTTP authentication requests and responses between a client and a back end system?

**Comment by andrecarlucci** [comment]
Hi @iosgitr ,
Yes, it copies all the headers back and forth.
What kind of authentication are you using?

**Comment by iosgitr** [comment]
NTLM in my test environment and will be using Kerberos in production.

**Comment by andrecarlucci** [comment]
I'm afraid it would be impossible to do that:  https://stackoverflow.com/questions/41936501/reverse-proxying-an-ntlm-protected-website

:(

**Comment by iosgitr** [comment]
I got it to work this morning.  Looking through the code, I noticed that [the status code is being copied](https://github.com/SharpTools/SharpReverseProxy/blob/138212f10c7bf6046f3e496c4106aeb2467d315c/src/SharpReverseProxy/ProxyMiddleware.cs#L63) only if a response modifier is present (ResponseModifier != null).  I hadn't had a need to set one yet for the HTTP auth test I was doing but this morning I set one that just copies the body as-is to see if the 401 status code would be transferred to the client.  Authentication worked as expected.  

Is there a reason the status code is only being copied within that [one condition](https://github.com/SharpTools/SharpReverseProxy/blob/138212f10c7bf6046f3e496c4106aeb2467d315c/src/SharpReverseProxy/ProxyMiddleware.cs#L61)?  Would it make sense to move it up immediately before that condition so that the status code is transferred to the client in all cases?

**Comment by andrecarlucci** [comment]
I guess we can't always trust StackOverflow, lol.

@iosgitr , this is a bug. Now I see why content type wasn't working for @gbiellem.
I'll fix it asap.

**Comment by iosgitr** [comment]
Thanks!

**Comment by andrecarlucci** [comment]
@iosgitr , SharpReverseProxy.1.3.11.nupkg is out.
Could you check if you have any other issues?

**Comment by andrecarlucci** [comment]
Hi @iosgitr , I'm closing this issue. If you still find anything wrong, just write something here and I will follow up :)

**Comment by mariusgiger** [comment]
Hi @iosgitr,
I am trying to get a similar scenario to work. How did you achieve ntlm auth to be passed?

**Comment by rifaterdemsahin** [comment]
also asked a similar one here
https://github.com/SharpTools/SharpReverseProxy/issues/25
