### ISSUE TITLE
possible bug introduced in latest commit

### ISSUE THREAD

**Issue by ainglese** [SharpTools/SharpReverseProxy#8]
Hi Andre, thanks for your work. i think there is a bug in version 1.3.11. I keep getting a "header collection could not be modified" errors. In the source code, i see that in the latest commit you've added this line:
```
// SendAsync removes chunking from the response. 
// This removes the header so it ...
context.Response.Headers.Remove("transfer-encoding");
```
[Line 73](https://github.com/SharpTools/SharpReverseProxy/blob/32cb791df9c6b091abbc129168ef90f55108a866/src/SharpReverseProxy/ProxyMiddleware.cs#L73)

after sending the response:
```
[await responseMessage.Content.CopyToAsync(context.Response.Body);]
```
[Line 68](https://github.com/SharpTools/SharpReverseProxy/blob/32cb791df9c6b091abbc129168ef90f55108a866/src/SharpReverseProxy/ProxyMiddleware.cs#L68)

downgrading to 1.3.10 works as expected

**Comment by andrecarlucci** [comment]
I'm looking into it right now. Thanks for pointing it out :)

**Comment by andrecarlucci** [comment]
Hi @ainglese 
Just fixed this. Also added some tests to avoid this in the future ;)
