### ISSUE TITLE
proxy is followin redirects

### ISSUE THREAD

**Issue by ainglese** [SharpTools/SharpReverseProxy#9]
https://github.com/SharpTools/SharpReverseProxy/blob/36d9297c8eca1d472ae06f2a579541f8cd90e107/src/SharpReverseProxy/ProxyMiddleware.cs#L17

maybe adding an option to disable following the redirects:
```
_httpClient = new HttpClient(_options.BackChannelMessageHandler ?? new HttpClientHandler()
            {
                 AllowAutoRedirect = false
            });
```

**Comment by andrecarlucci** [comment]
Hmm.. do you think the behavior should be always false? (never follow).
Or should we add an option for this?

**Comment by ainglese** [comment]
well i think the proxy should never follow the redirects, but i'm not a big fan of breaking changes and there may be a scenario where it could be needed so i think the best option here is to add an option and maybe default it to true (always follow)

**Comment by andrecarlucci** [comment]
@ainglese , ProxyOptions now has an option called `FollowRedirects`, default `true`.
Please, take a look if that fixes your issue.
Maybe we change that to default `false` when making the version 2.0 :)

**Comment by ainglese** [comment]
ehi, semVer rules!
thank you very much.

for your v2 version, i'm evaluating a scenario i'd like to share.
i have a "reduced" microservices scenario, where i have a windows service that must be deployed on windows server.
before everything: scaling is not a real issue here. those service are for small enterprises. what i want to accomplish is a blue/green deploy scenario, with an optional maintenance mode. i've already managed to get this configuration working, but i think a couple of things need to be added:
1. caching: i think this is pretty obvious, if content served from the backend service has the right headers, it gets cached on the proxy. i'm thinking of a memory cache to get started, i don't see the need for anything more complex; do you think this should be handled at the "proxy middleware" level, or maybe putting another middleware in front of the proxy?
2. health reporting: backend instances should get some sort of health reporting, when they fail, the proxy could switch configuration to another instance or fallback to maintenance mode. currently i'm handling this in a middleware in front of the proxy middleware (but maybe i should handle this in another pipeline binded to another, internal only port, but that's another story).
3. performances: maybe this is not critical (i need to do some meaningfull tests) but any advice or improvement area you think that need to be done?
Curiosity: do you think this is stable enought to be considered "production friendly"?
I know i can go the "iis + arr" way, but ehy, that's the easy way :)

**Comment by andrecarlucci** [comment]
Hi @ainglese,
I'm sorry it took so long to get back to you, but here it goes.
1. caching: yes, I believe this would be a task for another middleware. You could try [SharpCache](https://github.com/SharpTools/SharpCache) :)
2. That's interesting. We could implement a retry policy for every rule (filtered by http codes) and a circuit breaker action. I will keep that in mind :)
3. Not sure, I didn't do any hardcore testing, but I use SharpReverseProxy in our systems (production).

Cheers and thanks for all the feedback.
